IMAGE_NAME = "generic/ubuntu2004"
N = 1 #número de nodes desejados no cluster

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
     
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.56.10"
        master.vm.hostname = "k8s-master"
        master.vm.provider "virtualbox" do |master|
          master.customize ["modifyvm", :id, "--chipset", "ich9"]
          master.name = "k8s-master"
          master.memory = 8192
          master.cpus = 8
        end
        master.vm.provision "master-playbook", type:'ansible' do |ansible|
            ansible.playbook = "files/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.56.10",
            }
        end
        master.vm.provision "playbook", type:'ansible' do |ansible|
            ansible.playbook = "files/playbook.yml"
        end
    end

    (1..N).each do |i|
        config.vm.define "k8s-node0#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.56.#{i + 10}"
            node.vm.hostname = "k8s-node0#{i}"
            node.vm.provider "virtualbox" do |node|
                node.customize ["modifyvm", :id, "--chipset", "ich9"]
                node.name = "k8s-node0#{i}"
                node.memory = 2048
                node.cpus = 2
            end
            node.vm.provision "ansible", type:'ansible' do |ansible|
                ansible.playbook = "files/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.56.#{i + 10}",
                }
            end
            node.vm.provision "playbook", type:'ansible' do |ansible|
                ansible.playbook = "files/playbook.yml"
            end
        end
    end
end
