Vagrant.configure("2") do |config|
    config.vm.define "k8s"do |k8s|
        k8s.vm.box = "generic/ubuntu2004"
        k8s.vm.hostname = "kubernetes"
        k8s.vm.network "private_network", ip: "192.168.56.10", :netmask => "255.255.255.0"
        k8s.vm.provision "shell", path: "post-install.sh"
        k8s.vm.provision "shell", path: "install-kind.sh"
            k8s.vm.provider "virtualbox" do |vb|
              vb.name = "k8s"
              vb.memory = 8192
              vb.cpus = 8
            end
        end
    end