---
- hosts: all
  become: true
  tasks:

  - name: Instalando pacotes adicionais
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - chrony
      - nmap
      - zsh

  - name: Copiando arquivo .zshrc
    copy: src=.zshrc dest=/home/vagrant/.zshrc

  - name: Copiando arquivo nanorc
    copy: src=nanorc dest=/etc/nanorc

  - name: Copiando arquivo chrony.conf
    copy: src=chrony.conf dest=/etc/chrony/chrony.conf

  - name: Instalando Oh My Zsh
    git:
      repo: https://github.com/robbyrussell/oh-my-zsh.git
      dest: /etc/oh-my-zsh
      clone: yes
      update: yes    

  - name: Instalando zsh-syntax-highlighting
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: /etc/oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      clone: yes
      update: yes

  - name: Alterando o shell padrão do usuário vagrant
    user:
      name: "vagrant"
      shell: /bin/zsh

  - name: Configurando Timezone
    timezone:
      name: America/Sao_Paulo

  - name: Executando locale-gen
    locale_gen:
      name: pt_BR.UTF-8
      state: present

  - name: Alterando idioma
    command: localectl set-locale LANG=pt_BR.UTF-8

  - name: Configurando teclado
    shell:
      cmd: |
        localectl set-keymap br-abnt2

  - name: Reiniciando chrony
    service:
      name: chronyd
      daemon_reload: yes
      state: restarted
