Vagrant.configure("2") do |config|
config.vm.define "zbxserver"do |zbxserver|
    zbxserver.vm.box = "generic/centos8"
    zbxserver.vm.hostname = "zbxserver"
    zbxserver.vm.network "private_network", ip: "192.168.56.50", :netmask => "255.255.255.0"
    zbxserver.vm.provision "file", source: "files/.", destination: "/home/vagrant/"
    zbxserver.vm.provision "shell", path: "post-install.sh"
    zbxserver.vm.provision "shell", path: "install-zbx-server.sh"
    # zbxserver.vm.provision "shell", path: "install-grafana.sh"
        zbxserver.vm.provider "virtualbox" do |zbxserver|
          zbxserver.customize ["modifyvm", :id, "--chipset", "ich9"]
          zbxserver.name = "zbx-server"
          zbxserver.memory = 4096
          zbxserver.cpus = 4
        end
    end
config.vm.define "zbxproxy"do |zbxproxy|
    zbxproxy.vm.box = "generic/centos8"
    zbxproxy.vm.hostname = "zbxproxy"
    zbxproxy.vm.network "private_network", ip: "192.168.56.60", :netmask => "255.255.255.0"
    zbxproxy.vm.provision "file", source: "files/.", destination: "/home/vagrant/"
    zbxproxy.vm.provision "shell", path: "post-install.sh"
    zbxproxy.vm.provision "shell", path: "install-zbx-proxy.sh"
        zbxproxy.vm.provider "virtualbox" do |zbxproxy|
          zbxproxy.customize ["modifyvm", :id, "--chipset", "ich9"]
          zbxproxy.name = "zbxproxy"
          zbxproxy.memory = 2048
          zbxproxy.cpus = 2
        end
    end

config.vm.define "srv01" do |srv01|
    srv01.vm.box = "generic/centos8"
    srv01.vm.hostname = "srv01"
    srv01.vm.network "private_network", ip: "192.168.56.51", :netmask => "255.255.255.0"
    srv01.vm.provision "file", source: "files/.", destination: "/home/vagrant/"
    srv01.vm.provision "shell", path: "post-install.sh"
    srv01.vm.provision "shell", path: "install-zbx-agent.sh"
        srv01.vm.provider "virtualbox" do |srv01|
          srv01.customize ["modifyvm", :id, "--chipset", "ich9"]
          srv01.name = "srv01"
          srv01.memory = 2048
          srv01.cpus = 2
        end
    end

config.vm.define "srv02" do |srv02|
    srv02.vm.box = "StefanScherer/windows_2019"
    srv02.vm.hostname = "srv02"
    srv02.vm.network "private_network", ip: "192.168.56.52", :netmask => "255.255.255.0"
    srv02.vm.guest = :windows
    srv02.vm.boot_timeout = 600
    srv02.vm.communicator = 'winrm'
    srv02.winrm.port = 55985
    srv02.winrm.transport = :plaintext
    srv02.winrm.basic_auth_only = true
    srv02.winssh.shell = 'powershell'  
    srv02.vm.provision "shell", privileged: "true", path: "post-install.ps1"
        srv02.vm.provider "virtualbox" do |srv02|
          srv02.name = "srv02"    
          srv02.gui = false       
          srv02.memory = 4096
          srv02.cpus = 4
          srv02.customize ["modifyvm", :id, "--chipset", "ich9"]
          srv02.customize ["modifyvm", :id, "--draganddrop", "bidirectional"] 
          srv02.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        end
    end
end