Vagrant.configure("2") do |config|
    config.vm.define "kind"do |kind|
        kind.vm.box = "generic/ubuntu2004"
        kind.vm.hostname = "kind"
        kind.vm.network "private_network", ip: "192.168.56.10", :netmask => "255.255.255.0"
        kind.vm.provision "file", source: "files/.", destination: "/home/vagrant/"
        kind.vm.provision "shell", path: "post-install.sh"
        kind.vm.provision "shell", path: "install-kind.sh"
            kind.vm.provider "virtualbox" do |kind|
              kind.name = "kind"
              kind.memory = 8192
              kind.cpus = 8
            end
        end
    end